export const caseStudiesData = [
  {
    slug: "lemonide-tech",
    client: "Lemonide Tech",
    year: "2024",
    title: "Revolutionizing E-Commerce with AI",
    description: "A cutting-edge e-commerce platform integrating AI for personalized shopping experiences.",
    longDescription: "Lemonide Tech approached us to build a next-generation e-commerce platform. The goal was to integrate AI-driven recommendations and ensure a seamless, fast-loading user experience across all devices.",
    challenge: "The main challenge was to handle high traffic loads while performing real-time AI analysis for product recommendations without compromising site speed.",
    solution: "We utilized Next.js for server-side rendering and edge caching, combined with a custom AI model hosted on scalable cloud infrastructure. The UI was crafted with Tailwind CSS for responsiveness.",
    results: [
      "40% increase in conversion rates",
      "Sub-second page load times",
      "25% increase in average order value",
    ],
    features: [
      "AI Integration",
      "Responsive Design",
      "Custom Layouts",
      "Fast Loading",
    ],
    tags: ["E-Commerce", "Case Studies"],
    gradient: "from-[#EFFC76]/40 to-[#EFFC76]/40",
    images: ["/portfolio/watch.png", "/portfolio/phone.png"],
    liveLink: "https://example.com",
  },
  {
    slug: "viper-studio",
    client: "Viper Studio",
    year: "2025",
    title: "Modern Digital Agency Portfolio",
    description: "A sleek, high-performance portfolio site for a leading creative agency.",
    longDescription: "Viper Studio needed a digital presence that matched their creative output. We designed a typography-driven interface that puts their work front and center, backed by a flexible CMS.",
    challenge: "Creating a visually heavy site that remains performant and accessible, while giving the client full control over their content.",
    solution: "We built a headless CMS architecture using Sanity.io and Next.js, allowing for rich media content delivery without bloat. Framer Motion was used for smooth, non-intrusive animations.",
    results: [
      "Award-winning design recognition",
      "2x increase in client inquiries",
      "100/100 Lighthouse performance score",
    ],
    features: [
      "Modern Typography",
      "User Friendly",
      "Flexible CMS",
      "SEO Optimized",
    ],
    tags: ["Business", "Agency"],
    gradient: "from-[#EFFC76]/40 to-[#EFFC76]/40",
    images: ["/portfolio/cap.png", "/portfolio/woman.png"],
    liveLink: "https://example.com",
  },
  {
    slug: "million-one",
    client: "Million One",
    year: "2025",
    title: "High-Performance Corporate Identity",
    description: "A robust corporate website designed for scale and impact.",
    longDescription: "Million One required a corporate identity website that could scale with their rapid global expansion. We focused on performance, security, and a modular design system.",
    challenge: "Balancing strict corporate branding guidelines with modern interactive web standards.",
    solution: "We developed a custom design system and component library. The site features interactive data visualizations and a secure client portal.",
    results: [
      "Streamlined brand communication",
      "Reduced maintenance costs by 30%",
      "Successful global launch across 5 regions",
    ],
    features: [
      "Easy Customization",
      "Interactive Elements",
      "Retina Ready",
      "High Performance",
    ],
    tags: ["Case Studies", "Agency"],
    gradient: "from-[#EFFC76]/40 to-[#EFFC76]/40",
    images: ["/portfolio/car.png", "/portfolio/bottle.png"],
    liveLink: "https://example.com",
  },
];
