import {
  Code,
  Cloud,
  Smartphone,
  PenTool,
  TrendingUp,
  Palette,
  Globe,
  Monitor,
} from "lucide-react";

export const servicesData = [
  {
    slug: "web-development",
    icon: Code,
    title: "Web Development",
    subtitle: "Robust Solutions",
    description: "Building scalable, high-performance websites tailored to your business needs.",
    longDescription: "We craft high-performance, secure, and scalable web applications tailored to your business goals. From simple landing pages to complex enterprise platforms, our web development solutions ensure a seamless user experience across all devices.",
    features: ["Custom Web Applications", "E-commerce Solutions", "CMS Development", "Progressive Web Apps (PWA)"],
    benefits: ["Improved Site Performance", "Higher Conversion Rates", "SEO-Friendly Structure", "Scalable Architecture"],
  },
  {
    slug: "cloud-computing",
    icon: Cloud,
    title: "Cloud Computing",
    subtitle: "Scalable Infrastructure",
    description: "Secure and scalable cloud solutions to power your enterprise applications.",
    longDescription: "Leverage the power of the cloud to enhance your business agility and reduce infrastructure costs. We offer end-to-end cloud services including migration, management, and optimization on AWS, Azure, and Google Cloud.",
    features: ["Cloud Migration", "Serverless Architecture", "DevOps Automation", "Cloud Security"],
    benefits: ["Reduced IT Costs", "High Availability", "Automated Backups", "Global Scalability"],
  },
  {
    slug: "mobile-app-development",
    icon: Smartphone,
    title: "Mobile App Development",
    subtitle: "iOS & Android",
    description: "Native and cross-platform mobile apps that deliver exceptional user experiences.",
    longDescription: "Reach your customers on the go with our top-tier mobile application development services. We build native and cross-platform apps that combine stunning design with powerful functionality.",
    features: ["iOS & Android Apps", "React Native & Flutter", "App Store Optimization", "Mobile UI/UX"],
    benefits: ["Wider Market Reach", "Enhanced User Engagement", "Offline Functionality", "Brand Loyalty"],
  },
  {
    slug: "ui-ux-design",
    icon: PenTool,
    title: "UI/UX Design",
    subtitle: "User-Centric Design",
    description: "Creating intuitive and engaging interfaces that users love and trust.",
    longDescription: "Great design is about more than just aesthetics; it's about solving problems. Our UI/UX design process focuses on understanding your users to create intuitive, accessible, and delightful digital experiences.",
    features: ["User Research", "Wireframing & Prototyping", "Interaction Design", "Design Systems"],
    benefits: ["Increased User Satisfaction", "Lower Bounce Rates", "Brand Consistency", "Data-Driven Decisions"],
  },
  {
    slug: "digital-marketing",
    icon: TrendingUp,
    title: "Digital Marketing",
    subtitle: "Growth & Reach",
    description: "Data-driven marketing strategies to grow your brand and reach your audience.",
    longDescription: "Accelerate your growth with our comprehensive digital marketing strategies. We use data-driven insights to target the right audience, increase traffic, and convert visitors into loyal customers.",
    features: ["SEO & SEM", "Social Media Marketing", "Content Strategy", "Email Marketing"],
    benefits: ["Measurable ROI", "Targeted Audience Reach", "Brand Awareness", "Lead Generation"],
  },
  {
    slug: "graphic-design",
    icon: Palette,
    title: "Graphic Design",
    subtitle: "Visual Identity",
    description: "Stunning visuals and branding materials that make a lasting impression.",
    longDescription: "We create compelling visual identities that resonate with your audience. From logo design to marketing collaterals, our graphic design services help you stand out in a crowded marketplace.",
    features: ["Logo Design", "Brand Identity", "Marketing Materials", "Infographics"],
    benefits: ["Professional Image", "Brand Recognition", "Effective Communication", "Visual Appeal"],
  },
  {
    slug: "wordpress-development",
    icon: Globe,
    title: "WordPress Development",
    subtitle: "Custom Themes",
    description: "Expert WordPress development for flexible and easy-to-manage websites.",
    longDescription: "We specialize in custom WordPress development, creating unique themes and plugins that meet your specific requirements. Our WordPress sites are fast, secure, and easy to manage.",
    features: ["Custom Theme Development", "Plugin Development", "WooCommerce Integration", "Speed Optimization"],
    benefits: ["Easy Content Management", "Large Community Support", "SEO Friendly", "Customizable"],
  },
  {
    slug: "custom-software-development",
    icon: Monitor,
    title: "Custom Software Development",
    subtitle: "Tailored Solutions",
    description: "Bespoke software solutions designed to solve your specific business challenges.",
    longDescription: "When off-the-shelf software isn't enough, we build custom software solutions tailored to your unique business processes. We handle the entire development lifecycle, from requirements gathering to deployment and support.",
    features: ["Enterprise Software", "SaaS Development", "API Integration", "Legacy System Modernization"],
    benefits: ["Tailored to Your Needs", "Competitive Advantage", "Integration Capability", "Ownership & Control"],
  },
];
